name: production_deploy

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: deploy
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_HOST: ${{secrets.SERVER_HOST}}
          SSH_USERNAME: ${{secrets.SERVER_USERNAME}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key ${SERVER_USERNAME}@${SERVER_HOST} -o StrictHostKeyChecking=no "cd /var/www/test/test && \
          git pull origin master && \
	        cd /var/www/test/test && \
          #composer install”